### PR TITLE
Credit in qlxl

### PR DESCRIPTION
**Pull request by japari**
Hi Eric, GitHub reports the merge has to be done manually.
Some points though:
-> The CDS rule can not be used till the changes I am working with Peter are finished. It will complain about the protection dates if used instead of the OldCDS. See the sample worksheet.
-> I havent added the options yet.
There are lots of commits from QL master, shouldnt have updated. Anyway tell me if thats a problem.
Best
Pepe

### CODE REVIEW

**Comment by eehlers** [comment]
Hey Pepe... I hope soon to deploy the release from my v1.5.0 branch.  Can I merge this pull request into that?  Or do you need to create a new one?  Cheers, Eric

**Comment by japari** [comment]
Hi Eric,
Great, it should work all right; everything there its pretty much orthogonal to the existing code. I'll try to find time to patch your branch to double check anyway; tell you if there's trouble.
Best
Pepe


----- Original Message -----

**Comment by eehlers** [comment]
Hi Pepe,

With regard to your two pull requests, I merged the older one ("Credit in qlxl") to my v1.5.0 branch, commited, and pushed to my remote repo.  Could you check it and see if it's OK?

Then I merged the newer one ("Latent qlxl").  This generated a ton of conflicts.  I went back to a clean slate and tried merging the two pull requests in the other sequence - "Latent" then "Credit" - and I got fewer conflicts, but still a lot.  So this is beyond my abilities.

Could you create a new pull request for "Latent" against my v1.5.0 branch?

Thanks,
Eric

**Comment by japari** [comment]
I am on it, tell you later.
Thank you
Pepe


----- Original Message -----

**Comment by japari** [comment]
Hi Eric, 
Its fixed now. Just a bit of manual merge did the trick. It was far too many changes for the automerge to get it right.
I will send you a PR tomorrow, just want to run the worksheets again.
Best
Pepe


----- Original Message -----

**Comment by eehlers** [comment]
merged.

**Pull request closed without merging**
