### PR TITLE
Lm 1.5.0 xl

### PR DESCRIPTION
**Pull request by japari**
Eric, can you try this one now please? Tell me if theres trouble. I have updated config files for my kit only: VC9 boost 1.570 32bits
Best

### CODE REVIEW

**Comment by eehlers** [comment]
I just attempted the merge, there were no conflicts, but there was another problem.

You have modified four QuantLib files:

QuantLib/QuantLib_vc9.vcproj
QuantLib/ql/experimental/credit/binomiallossmodel.hpp
QuantLib/ql/experimental/credit/recursivelossmodel.hpp
QuantLib/ql/experimental/credit/saddlepointlossmodel.hpp

This is a problem because I am not releasing QuantLib.  I am preparing the release of gensrc / ObjectHandler / QuantLibAddin / QuantLibXL version 1.5.0.  This is supposed to be compatible with the release of QuantLib 1.5.0 that has already shipped.

If your changes to QLA / QLXL are dependent upon these new changes to QL, then that will not work, because the 1.5.0 release of QLA / QLXL will not be compatible with the 1.5.0 release of QL.  Instead we would have to get these changes into Luigi's QL master, and then include them in some future release.

Please let me know.

Kind Regards,
Eric

**Comment by japari** [comment]
Hi Eric,
Of course. But this was unintended. It is supposed to be aligned with the QL release you are based on. I must have done something wrong with the merge. 
Let me fix it and come back to you.
Best
Pepe

----- Original Message -----

**Comment by japari** [comment]
Hi Eric,
should be mended now.
Thank you.
Pepe


----- Original Message -----

**Comment by eehlers** [comment]
Hey Pepe,
Many thanks for this.  I merged and pushed to my remote v1.5.0 branch.  Would you have a moment to check and see if it's OK?
I put your new example workbooks in the Standalone directory because the Workbooks directory is owned by the Excel VBA app.
Kind Regards,
Eric

**Comment by japari** [comment]
Hi Eric,
It works fine; I recompiled and ran the worksheets. Yes, I wasn't sure where to put them. If only, can you put the credit portfolio risk ones in a separate subfolder? (./Credit/PortfRisk/ or similar) Just to make the point they refer to each other and should be used together. 
Thank you
Pepe

**Comment by eehlers** [comment]
Hey Pepe,
I put your workbooks in StandaloneExamples/CreditPortfolioRisk.  The release has shipped, many thanks again for your help!
Kind Regards,
Eric

**Pull request closed without merging**
